# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.npc.node.head] at @s run function animated_java:npc/variants/steve_/zzz/apply_to_node_head
execute on passengers if entity @s[tag=aj.npc.node.right_arm] at @s run function animated_java:npc/variants/steve_/zzz/apply_to_node_right_arm
execute on passengers if entity @s[tag=aj.npc.node.left_arm] at @s run function animated_java:npc/variants/steve_/zzz/apply_to_node_left_arm
execute on passengers if entity @s[tag=aj.npc.node.body] at @s run function animated_java:npc/variants/steve_/zzz/apply_to_node_body
execute on passengers if entity @s[tag=aj.npc.node.right_leg] at @s run function animated_java:npc/variants/steve_/zzz/apply_to_node_right_leg
execute on passengers if entity @s[tag=aj.npc.node.left_leg] at @s run function animated_java:npc/variants/steve_/zzz/apply_to_node_left_leg
return 1