# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'bbe700b99e09da70213ca1313e9ed81c058202f6ad423aa648520dc41c186eeb'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack