# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.standing1.frame matches 201.. run scoreboard players set @s aj.standing1.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.standing1.frame
execute at @s run function animated_java:npc/animations/standing1/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.standing1.frame 1