# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:npc rig_hash set value 'bbe700b99e09da70213ca1313e9ed81c058202f6ad423aa648520dc41c186eeb'
scoreboard objectives add aj.standing1.frame dummy
scoreboard objectives add aj.standing2.frame dummy
scoreboard objectives add aj.sitting1.frame dummy
scoreboard objectives add aj.sitting2.frame dummy