# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.sitting2.frame matches 178.. run scoreboard players set @s aj.sitting2.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.sitting2.frame
execute at @s run function animated_java:npc/animations/sitting2/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.sitting2.frame 1