# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:npc/animations/standing2/zzz/apply_frame {frame: 200}
scoreboard players add @s aj.standing2.frame 1