# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:npc/animations/sitting2/zzz/apply_frame {frame: 177}
scoreboard players add @s aj.sitting2.frame 1