# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.npc.root] run return 0
execute if entity @s[tag=aj.npc.animation.standing1.playing] run function animated_java:npc/animations/standing1/zzz/on_tick
execute if entity @s[tag=aj.npc.animation.standing2.playing] run function animated_java:npc/animations/standing2/zzz/on_tick
execute if entity @s[tag=aj.npc.animation.sitting1.playing] run function animated_java:npc/animations/sitting1/zzz/on_tick
execute if entity @s[tag=aj.npc.animation.sitting2.playing] run function animated_java:npc/animations/sitting2/zzz/on_tick
execute on passengers run rotate @s ~ ~