# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.npc.animation.standing1.playing
tag @s remove aj.npc.animation.standing2.playing
tag @s remove aj.npc.animation.sitting1.playing
tag @s remove aj.npc.animation.sitting2.playing