# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:npc/animations/sitting1/zzz/apply_frame {frame: 211}
scoreboard players add @s aj.sitting1.frame 1